- run:
          name: "Compile Kernel"
          command: |
            cd kernel-6.6
            export PARENT_DIR=$(readlink -f ..)
            export ARCH=arm64
            export SUBARCH=arm64
            export CROSS_COMPILE=$PARENT_DIR/aarch64-linux-android-4.9/bin/aarch64-linux-android-
            export CLANG_TRIPLE=$PARENT_DIR/clang-r383902/bin/aarch64-linux-gnu-
            export PATH=$PATH:$PARENT_DIR/aarch64-linux-android-4.9/bin:$PARENT_DIR/clang-r383902/bin
            export LLVM=1
            
            # Explicitly tell make where to look and what architecture to use
            make O=out ARCH=arm64 afaneh_a34x_defconfig
            make O=out ARCH=arm64 -j$(nproc)