- run:
          name: "Download Modern Toolchain"
          command: |
            cd ..
            # We are getting a newer Clang (r416183b or similar) that supports Kernel 6.6
            git clone --depth=1 https://gitlab.com/tony_ark/prebuilts_clang_host_linux-x86_clang-r416183b clang-stable
            git clone --depth=1 --branch android-9.0.0_r59 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 aarch64-linux-android-4.9
      - run:
          name: "Compile Kernel"
          command: |
            cd kernel-6.6
            export PARENT_DIR=$(readlink -f ..)
            export ARCH=arm64
            export SUBARCH=arm64
            
            # Update these paths to match the 'clang-stable' folder we just made
            export CLANG_DIR=$PARENT_DIR/clang-stable
            export GCC_DIR=$PARENT_DIR/aarch64-linux-android-4.9
            
            export CROSS_COMPILE=$GCC_DIR/bin/aarch64-linux-android-
            export CLANG_TRIPLE=aarch64-linux-gnu-
            
            # IMPORTANT: Put the new Clang at the FRONT of the PATH so it overrides the old system Clang
            export PATH=$CLANG_DIR/bin:$GCC_DIR/bin:$PATH
            
            export LLVM=1
            export LLVM_IAS=1
            
            mkdir -p out
            make O=out ARCH=arm64 afaneh_a34x_defconfig
            make O=out ARCH=arm64 -j$(nproc)